import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Greet from '@/components/Greet';
import GreetPeople from '@/components/GreetPeople';
import Loading from '@/components/Loading';

export default function Home() {
	const inputChangeHandler = (e : React.ChangeEvent<HTMLInputElement>) => {
		console.log('event is: ', e.target.value);
	};

	const mystyle: React.CSSProperties = {
		border: '2px solid black',
		position: 'fixed',
	};

	const people = [
		{ first: 'Deependu', last: 'Jha' },
		{ first: 'Nitesh', last: 'Kumar' },
		{ first: 'Amrit', last: 'Anand' },
		{ first: 'Virat', last: 'Kohli' },
		{ first: 'Nithin', last: 'Kamath' },
	];
	
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Greet name="Deependu" unreadMessages={20} isLoggedIn={true} />
				<hr />
				<GreetPeople people={people} />
			</div>
			<hr />
			<div>
				<Loading loading_status="success" />
			</div>
			<hr />
			<div style={mystyle}>
				<input
					onChange={inputChangeHandler}
					placeholder="type here and see in console"
				/>
			</div>
		</>
	);
}
